### ISSUE TITLE
Error trying to get the example to work.

### ISSUE THREAD

**Issue by Florian-Roessler** [mcrowson/zappa_dash#1]
Hi I am new to zappa and AWS lambda but really curious about it so I followed your example except removing the domain related setting in the zappa_settings.json. Now I get the following error:

`
"{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', 'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 433, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/var/task/werkzeug/wrappers.py\", line 903, in from_app\\n    return cls(*_run_wsgi_app(app, environ, buffered))\\n', '  File \"/var/task/werkzeug/test.py\", line 884, in run_wsgi_app\\n    app_rv = app(environ, start_response)\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"
`
Is that an issue relating to the domain section or something else?

`zappa tail` tells me that there is a missing dependency `["numpy"]` even though it is installed.

Any idea what is happening?

edit: Just saw a related issue mentioning that it might be the total size that is larger than Lambda allows. However, not sure this is an issue as this example has been working for you?

**Comment by mcrowson** [comment]
If you followed the steps in the readme it should have installed numpy in your virtual env. Do a pip freeze locally and see if numpy is there.

**Comment by Florian-Roessler** [comment]
Yes it's there locally, I checked that before.

pip freeze result: 
```pip freeze                                                                                                                                                                                                       
argcomplete==1.8.2
base58==0.2.4
boto3==1.4.4
botocore==1.5.40
certifi==2017.4.17
chardet==3.0.4
click==6.7
dash==0.17.5
dash-core-components==0.5.0
dash-html-components==0.6.1
dash-renderer==0.7.3
dash.ly==0.17.3
decorator==4.0.11
docutils==0.13.1
durationpy==0.4
Flask==0.12.2
Flask-Compress==1.4.0
Flask-SeaSurf==0.2.2
future==0.16.0
futures==3.1.1
hjson==2.0.7
idna==2.5
ipython-genutils==0.2.0
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.3
jsonschema==2.6.0
jupyter-core==4.3.0
kappa==0.6.0
lambda-packages==0.15.1
MarkupSafe==1.0
nbformat==4.3.0
numpy==1.13.0
pandas==0.20.2
placebo==0.8.1
plotly==2.0.10
python-dateutil==2.6.0
python-slugify==1.2.4
pytz==2017.2
PyYAML==3.12
requests==2.18.1
s3transfer==0.1.10
six==1.10.0
toml==0.9.2
tqdm==4.14.0
traitlets==4.3.2
troposphere==1.9.4
Unidecode==0.4.21
urllib3==1.21.1
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.42.2```

what kind of error would I expect if I use the link that zappa returns as opposed to using your subdomain approach?

**Comment by mcrowson** [comment]
that Nonetype error means that the flask app isn't loading successfully. So Zappa is attempting to call your flask application but there is no flask application (because it failed to load). The failure to load seems to be from the lack of numpy, but you have numpy. 

Do note that if you don't have a domain set, that it probably won't work (or at least I haven't figured it out). API Gateway will give you some URL for the application with the /dev/ stage name at the root.  Check out the issue I linked to in the Readme for details.

**Comment by Florian-Roessler** [comment]
Thanks for the answers, I think I got it working to a stage were I need a subdomain for it to work properly. It was a matter of pip pointing to the wrong binary in one of my terminals... 

Also for a newbie could you elaborate a bit on what this bit of code does:
```
app = dash.Dash()
app.server.secret_key = 'notterriblysecret'
server = app.server
```

**Comment by mcrowson** [comment]
the app is your Dash app. the app.server is your Flask server. The Flask
server needs a secret_key parameter for https requests. The line where we
create the server variable is so that Zappa knows where the Flask server is
to call. The server variable is referenced in the zappa_settings.json file.

**Comment by Florian-Roessler** [comment]
ah ok. 
In that case the in zappa_settings.json it should say: `"app_function": "app.server"` instead of `"app_function": "app.app"` right?

**Comment by mcrowson** [comment]
yea! I stopped tracking my real zappa_settings.py file because it had my account stuff for the AWS Certificate manager stuff, I guess I forgot to make that change on this one.
